export type SunRequirement = 'full_sun' | 'partial_sun' | 'partial_shade' | 'full_shade';
export type WaterNeed = 'low' | 'moderate' | 'high';
export type FrostTolerance = 'hardy' | 'semi_hardy' | 'tender';
export type BedType = 'raised' | 'in_ground' | 'container' | 'barrel' | 'hanging' | 'trellis' | 'trough';
export type PlantStatus = 'planned' | 'seeded' | 'sprouted' | 'hardening' | 'transplanted' | 'growing' | 'harvesting' | 'done';
export type TaskStatus = 'pending' | 'completed';

export interface Plant {
  id: string;
  common_name: string;
  botanical_name: string;
  family: string;
  icon: string;
  color: string;
  sun_requirement: SunRequirement;
  water_need: WaterNeed;
  frost_tolerance: FrostTolerance;
  spacing_per_sqft: number;
  days_to_maturity: number;
  seed_start_weeks_before_frost: number | null;
  zone_4_transplant_date: string | null;
  zone_4_direct_sow_date: string | null;
  zone_4_seed_start_date: string | null;
  harvest_start_date: string | null;
  harvest_end_date: string | null;
  companions_good: string[];
  companions_bad: string[];
  crop_rotation_family: string;
  growth_habit: string;
  needs_support: boolean;
  yield_per_plant_lbs: number;
  description: string;
  growing_tips: string[];
  pests: string[];
  varieties: string[];
  tags: string[];
}

export interface BedSquare {
  plantId: string | null;
  status: PlantStatus;
  plantedDate: string | null;
  notes: string;
}

export interface GardenBed {
  id: string;
  name: string;
  type: BedType;
  widthFt: number;
  lengthFt: number;
  sunExposure: SunRequirement;
  squares: BedSquare[][];
  // Canvas position (feet from origin)
  x?: number;
  y?: number;
}

export interface PropertyConfig {
  lot_width_ft: number;
  lot_depth_ft: number;
  house_x: number;
  house_y: number;
  house_width_ft: number;
  house_depth_ft: number;
  orientation_deg: number; // 0 = north at top
}

export interface GardenTask {
  id: string;
  title: string;
  description: string;
  dueDate: string;
  status: TaskStatus;
  completedDate: string | null;
  plantId: string | null;
  bedId: string | null;
  category: 'seeding' | 'transplanting' | 'watering' | 'harvesting' | 'maintenance' | 'other';
  autoGenerated: boolean;
}

export interface HarvestLog {
  id: string;
  plantId: string;
  bedId: string;
  date: string;
  quantityLbs: number;
  notes: string;
}

export interface ShoppingItem {
  id: string;
  name: string;
  category: 'seeds' | 'transplants' | 'soil_amendments' | 'infrastructure' | 'tools';
  quantity: number;
  unit: string;
  estimatedCost: number;
  purchased: boolean;
  plantId: string | null;
}

export interface GardenSpec {
  version: string;
  zone: string;
  lastFrostDate: string;
  firstFrostDate: string;
  beds: GardenBed[];
  tasks: GardenTask[];
  harvestLog: HarvestLog[];
  shoppingList: ShoppingItem[];
  property?: PropertyConfig;
  createdAt: string;
  updatedAt: string;
}
