import React, { useState, useMemo } from 'react';
import { GardenSpec, GardenTask, HarvestLog } from '../types/garden';
import { getPlantById } from '../data/plants';

interface TaskManagerProps {
  spec: GardenSpec;
  onAddTask: (task: Omit<GardenTask, 'id'>) => string;
  onUpdateTask: (taskId: string, updates: Partial<GardenTask>) => void;
  onRemoveTask: (taskId: string) => void;
  onAddHarvest: (entry: Omit<HarvestLog, 'id'>) => void;
}

type TabView = 'tasks' | 'harvest';

const categoryIcons: Record<string, string> = {
  seeding: '🌱',
  transplanting: '🪴',
  watering: '💧',
  harvesting: '🧺',
  maintenance: '🔧',
  other: '📝',
};

export const TaskManager: React.FC<TaskManagerProps> = ({
  spec, onAddTask, onUpdateTask, onRemoveTask, onAddHarvest
}) => {
  const [tab, setTab] = useState<TabView>('tasks');
  const [showNewTask, setShowNewTask] = useState(false);
  const [showNewHarvest, setShowNewHarvest] = useState(false);
  const [showCompleted, setShowCompleted] = useState(false);
  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    dueDate: new Date().toISOString().split('T')[0],
    category: 'other' as GardenTask['category'],
    plantId: null as string | null,
    bedId: null as string | null,
  });
  const [newHarvest, setNewHarvest] = useState({
    plantId: '',
    bedId: '',
    date: new Date().toISOString().split('T')[0],
    quantityLbs: 0,
    notes: '',
  });

  const pendingTasks = useMemo(() =>
    spec.tasks.filter(t => t.status === 'pending').sort((a, b) => a.dueDate.localeCompare(b.dueDate)),
    [spec.tasks]
  );

  const completedTasks = useMemo(() =>
    spec.tasks.filter(t => t.status === 'completed').sort((a, b) =>
      (b.completedDate || '').localeCompare(a.completedDate || '')),
    [spec.tasks]
  );

  const totalHarvested = useMemo(() =>
    spec.harvestLog.reduce((sum, h) => sum + h.quantityLbs, 0),
    [spec.harvestLog]
  );

  const plantIdsInGarden = useMemo(() => {
    const ids = new Set<string>();
    spec.beds.forEach(b => b.squares.flat().forEach(s => { if (s.plantId) ids.add(s.plantId); }));
    return Array.from(ids);
  }, [spec]);

  const handleCreateTask = () => {
    if (!newTask.title.trim()) return;
    onAddTask({
      ...newTask,
      status: 'pending',
      completedDate: null,
      autoGenerated: false,
    });
    setNewTask({
      title: '', description: '', dueDate: new Date().toISOString().split('T')[0],
      category: 'other', plantId: null, bedId: null,
    });
    setShowNewTask(false);
  };

  const handleToggleTask = (task: GardenTask) => {
    if (task.status === 'pending') {
      onUpdateTask(task.id, { status: 'completed', completedDate: new Date().toISOString() });
    } else {
      onUpdateTask(task.id, { status: 'pending', completedDate: null });
    }
  };

  const handleAddHarvest = () => {
    if (!newHarvest.plantId || newHarvest.quantityLbs <= 0) return;
    onAddHarvest(newHarvest);
    setNewHarvest({ plantId: '', bedId: '', date: new Date().toISOString().split('T')[0], quantityLbs: 0, notes: '' });
    setShowNewHarvest(false);
  };

  const formatTaskDate = (dateStr: string) => {
    const date = new Date(dateStr + 'T12:00:00');
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  const isOverdue = (dueDate: string) => {
    return new Date(dueDate) < new Date('2026-03-24');
  };

  return (
    <div className="p-8 max-w-5xl mx-auto page-enter space-y-6">
      <div>
        <p className="text-xs font-medium uppercase tracking-[0.2em] mb-2" style={{ color: 'rgba(95,154,100,0.7)' }}>Tasks</p>
        <h1 className="text-4xl text-parchment-900 italic" style={{ fontFamily: 'var(--font-display)' }}>Tend Your Garden</h1>
        <p className="text-parchment-500 text-sm mt-1">Every great garden begins with a single seed</p>
        <div className="leaf-divider mt-5 mb-1" />
      </div>

      {/* Tabs */}
      <div className="flex gap-2 border-b border-earth-200 pb-0">
        <button
          onClick={() => setTab('tasks')}
          className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px ${
            tab === 'tasks' ? 'border-forest-600 text-forest-700' : 'border-transparent text-soil-400 hover:text-soil-600'
          }`}
        >
          Tasks ({pendingTasks.length} pending)
        </button>
        <button
          onClick={() => setTab('harvest')}
          className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px ${
            tab === 'harvest' ? 'border-forest-600 text-forest-700' : 'border-transparent text-soil-400 hover:text-soil-600'
          }`}
        >
          Harvest Log ({spec.harvestLog.length})
        </button>
      </div>

      {tab === 'tasks' && (
        <div className="space-y-4">
          {/* Add Task */}
          <div className="flex gap-2">
            <button
              onClick={() => setShowNewTask(true)}
              className="px-4 py-2 bg-forest-600 text-white rounded-lg text-sm font-medium hover:bg-forest-700 transition-colors"
            >
              + New Task
            </button>
            <button
              onClick={() => setShowCompleted(!showCompleted)}
              className="px-4 py-2 bg-white border border-earth-300 text-soil-600 rounded-lg text-sm hover:bg-earth-50 transition-colors"
            >
              {showCompleted ? 'Hide' : 'Show'} Completed ({completedTasks.length})
            </button>
          </div>

          {showNewTask && (
            <div className="bg-white rounded-xl border border-earth-200 p-4 shadow-sm">
              <h3 className="font-medium text-soil-700 mb-3">New Task</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="col-span-2">
                  <input
                    type="text"
                    placeholder="Task title..."
                    value={newTask.title}
                    onChange={e => setNewTask(p => ({ ...p, title: e.target.value }))}
                    className="w-full border border-earth-300 rounded-lg px-3 py-2 text-sm"
                    autoFocus
                  />
                </div>
                <div>
                  <input
                    type="date"
                    value={newTask.dueDate}
                    onChange={e => setNewTask(p => ({ ...p, dueDate: e.target.value }))}
                    className="w-full border border-earth-300 rounded-lg px-3 py-2 text-sm"
                  />
                </div>
                <div>
                  <select
                    value={newTask.category}
                    onChange={e => setNewTask(p => ({ ...p, category: e.target.value as any }))}
                    className="w-full border border-earth-300 rounded-lg px-3 py-2 text-sm"
                  >
                    <option value="seeding">Seeding</option>
                    <option value="transplanting">Transplanting</option>
                    <option value="watering">Watering</option>
                    <option value="harvesting">Harvesting</option>
                    <option value="maintenance">Maintenance</option>
                    <option value="other">Other</option>
                  </select>
                </div>
              </div>
              <textarea
                placeholder="Description (optional)..."
                value={newTask.description}
                onChange={e => setNewTask(p => ({ ...p, description: e.target.value }))}
                className="w-full border border-earth-300 rounded-lg px-3 py-2 text-sm mt-2"
                rows={2}
              />
              <div className="mt-3 flex gap-2">
                <button onClick={handleCreateTask}
                  className="px-4 py-2 bg-forest-600 text-white rounded-lg text-sm hover:bg-forest-700">
                  Create Task
                </button>
                <button onClick={() => setShowNewTask(false)}
                  className="px-4 py-2 text-soil-400 text-sm hover:text-soil-600">
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* Pending Tasks */}
          {pendingTasks.length === 0 ? (
            <div className="bg-white rounded-xl border border-earth-200 p-8 text-center shadow-sm">
              <span className="text-4xl block mb-3">✅</span>
              <p className="text-soil-500">No pending tasks. Add some or they will be auto-generated from your planting dates!</p>
            </div>
          ) : (
            <div className="space-y-2">
              {pendingTasks.map(task => {
                const plant = task.plantId ? getPlantById(task.plantId) : null;
                const overdue = isOverdue(task.dueDate);
                return (
                  <div key={task.id} className={`bg-white rounded-lg border p-3 shadow-sm flex items-start gap-3 transition-colors ${
                    overdue ? 'border-red-200 bg-red-50/50' : 'border-earth-200'
                  }`}>
                    <button
                      onClick={() => handleToggleTask(task)}
                      className="w-5 h-5 rounded border-2 border-earth-300 hover:border-forest-500 mt-0.5 shrink-0 flex items-center justify-center transition-colors"
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm">{categoryIcons[task.category]}</span>
                        <p className="text-sm font-medium text-soil-700">{task.title}</p>
                        {plant && <span className="text-xs text-soil-400">{plant.icon} {plant.common_name}</span>}
                      </div>
                      {task.description && (
                        <p className="text-xs text-soil-500 mt-0.5">{task.description}</p>
                      )}
                      <p className={`text-xs mt-1 ${overdue ? 'text-red-600 font-medium' : 'text-soil-400'}`}>
                        {overdue ? 'Overdue: ' : 'Due: '}{formatTaskDate(task.dueDate)}
                      </p>
                    </div>
                    <button
                      onClick={() => onRemoveTask(task.id)}
                      className="text-soil-300 hover:text-red-500 text-sm shrink-0"
                    >
                      &times;
                    </button>
                  </div>
                );
              })}
            </div>
          )}

          {/* Completed Tasks */}
          {showCompleted && completedTasks.length > 0 && (
            <div className="space-y-2 opacity-60">
              <h3 className="text-sm font-medium text-soil-500 mt-4">Completed</h3>
              {completedTasks.map(task => (
                <div key={task.id} className="bg-white rounded-lg border border-earth-200 p-3 shadow-sm flex items-start gap-3">
                  <button
                    onClick={() => handleToggleTask(task)}
                    className="w-5 h-5 rounded border-2 border-forest-400 bg-forest-400 mt-0.5 shrink-0 flex items-center justify-center"
                  >
                    <span className="text-white text-xs">&#10003;</span>
                  </button>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-soil-500 line-through">{task.title}</p>
                    {task.completedDate && (
                      <p className="text-xs text-soil-400">Completed {new Date(task.completedDate).toLocaleDateString()}</p>
                    )}
                  </div>
                  <button onClick={() => onRemoveTask(task.id)}
                    className="text-soil-300 hover:text-red-500 text-sm">&times;</button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {tab === 'harvest' && (
        <div className="space-y-4">
          {/* Stats */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-white rounded-xl border border-earth-200 p-4 text-center shadow-sm">
              <p className="text-sm text-soil-500">Total Harvested</p>
              <p className="text-2xl font-bold text-harvest-600">{totalHarvested.toFixed(1)} lbs</p>
            </div>
            <div className="bg-white rounded-xl border border-earth-200 p-4 text-center shadow-sm">
              <p className="text-sm text-soil-500">Harvest Entries</p>
              <p className="text-2xl font-bold text-forest-600">{spec.harvestLog.length}</p>
            </div>
            <div className="bg-white rounded-xl border border-earth-200 p-4 text-center shadow-sm">
              <p className="text-sm text-soil-500">Crops Harvested</p>
              <p className="text-2xl font-bold text-forest-600">
                {new Set(spec.harvestLog.map(h => h.plantId)).size}
              </p>
            </div>
          </div>

          <button
            onClick={() => setShowNewHarvest(true)}
            className="px-4 py-2 bg-harvest-500 text-white rounded-lg text-sm font-medium hover:bg-harvest-600 transition-colors"
          >
            + Log Harvest
          </button>

          {showNewHarvest && (
            <div className="bg-white rounded-xl border border-earth-200 p-4 shadow-sm">
              <h3 className="font-medium text-soil-700 mb-3">Log a Harvest</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <select
                  value={newHarvest.plantId}
                  onChange={e => setNewHarvest(p => ({ ...p, plantId: e.target.value }))}
                  className="border border-earth-300 rounded-lg px-3 py-2 text-sm"
                >
                  <option value="">Select plant...</option>
                  {plantIdsInGarden.map(id => {
                    const p = getPlantById(id);
                    return p ? <option key={id} value={id}>{p.icon} {p.common_name}</option> : null;
                  })}
                </select>
                <select
                  value={newHarvest.bedId}
                  onChange={e => setNewHarvest(p => ({ ...p, bedId: e.target.value }))}
                  className="border border-earth-300 rounded-lg px-3 py-2 text-sm"
                >
                  <option value="">Select bed...</option>
                  {spec.beds.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
                </select>
                <input
                  type="number"
                  min={0}
                  step={0.1}
                  placeholder="Pounds"
                  value={newHarvest.quantityLbs || ''}
                  onChange={e => setNewHarvest(p => ({ ...p, quantityLbs: Number(e.target.value) }))}
                  className="border border-earth-300 rounded-lg px-3 py-2 text-sm"
                />
                <input
                  type="date"
                  value={newHarvest.date}
                  onChange={e => setNewHarvest(p => ({ ...p, date: e.target.value }))}
                  className="border border-earth-300 rounded-lg px-3 py-2 text-sm"
                />
              </div>
              <input
                type="text"
                placeholder="Notes (optional)"
                value={newHarvest.notes}
                onChange={e => setNewHarvest(p => ({ ...p, notes: e.target.value }))}
                className="w-full border border-earth-300 rounded-lg px-3 py-2 text-sm mt-2"
              />
              <div className="mt-3 flex gap-2">
                <button onClick={handleAddHarvest}
                  className="px-4 py-2 bg-harvest-500 text-white rounded-lg text-sm hover:bg-harvest-600">
                  Log Harvest
                </button>
                <button onClick={() => setShowNewHarvest(false)}
                  className="px-4 py-2 text-soil-400 text-sm hover:text-soil-600">
                  Cancel
                </button>
              </div>
            </div>
          )}

          {/* Harvest Log */}
          {spec.harvestLog.length === 0 ? (
            <div className="bg-white rounded-xl border border-earth-200 p-8 text-center shadow-sm">
              <span className="text-4xl block mb-3">🧺</span>
              <p className="text-soil-500">No harvest entries yet. Log your first harvest when it's time!</p>
            </div>
          ) : (
            <div className="bg-white rounded-xl border border-earth-200 shadow-sm overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-earth-50 border-b border-earth-200">
                    <th className="text-left px-4 py-2 text-soil-500 font-medium">Date</th>
                    <th className="text-left px-4 py-2 text-soil-500 font-medium">Plant</th>
                    <th className="text-left px-4 py-2 text-soil-500 font-medium">Bed</th>
                    <th className="text-right px-4 py-2 text-soil-500 font-medium">Amount</th>
                    <th className="text-left px-4 py-2 text-soil-500 font-medium">Notes</th>
                  </tr>
                </thead>
                <tbody>
                  {[...spec.harvestLog].reverse().map(entry => {
                    const plant = getPlantById(entry.plantId);
                    const bed = spec.beds.find(b => b.id === entry.bedId);
                    return (
                      <tr key={entry.id} className="border-b border-earth-100">
                        <td className="px-4 py-2 text-soil-600">{new Date(entry.date + 'T12:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</td>
                        <td className="px-4 py-2">{plant ? `${plant.icon} ${plant.common_name}` : entry.plantId}</td>
                        <td className="px-4 py-2 text-soil-500">{bed?.name || '-'}</td>
                        <td className="px-4 py-2 text-right font-medium">{entry.quantityLbs} lbs</td>
                        <td className="px-4 py-2 text-soil-500">{entry.notes || '-'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
